#!/bin/sh
 
mount -t proc none /proc
mount -t sysfs none /sys

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

insmod /lib/modules/netmap.ko
insmod /lib/modules/e1000.ko

ifconfig eth0 up
ADDR_SUFFIX=$(ifconfig|grep HWaddr|sed 's/.*://g')
ifconfig eth0 192.168.34.$ADDR_SUFFIX

echo -e "\nBoot took $(cut -d' ' -f1 /proc/uptime) seconds\n"
 
setsid cttyhack sh
